use backwards compatible error message
The test was failing because the error messages differn in different CPython versions:

See:

```
Python 3.5.3 (default, May 22 2017, 14:45:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b'abc'.index(b'def')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: substring not found
```

vs

```
$ $(pythonz locate 3.6.1)
Python 3.6.1 (default, Mar 31 2017, 13:11:57) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b'abc'.index(b'def')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: subsection not found
```